<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MatchSeeder extends Seeder
{
    public function run(): void
    {
        $flags = [
            'México' => '🇲🇽',
            'Sudáfrica' => '🇿🇦',
            'Corea del Sur' => '🇰🇷',
            'República Checa' => '🇨🇿',
            'Canadá' => '🇨🇦',
            'Bosnia y Herzegovina' => '🇧🇦',
            'Qatar' => '🇶🇦',
            'Suiza' => '🇨🇭',
            'Brasil' => '🇧🇷',
            'Marruecos' => '🇲🇦',
            'Haití' => '🇭🇹',
            'Escocia' => '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
            'Estados Unidos' => '🇺🇸',
            'Paraguay' => '🇵🇾',
            'Australia' => '🇦🇺',
            'Turquía' => '🇹🇷',
            'Alemania' => '🇩🇪',
            'Curazao' => '🇨🇼',
            'Costa de Marfil' => '🇨🇮',
            'Ecuador' => '🇪🇨',
            'Países Bajos' => '🇳🇱',
            'Japón' => '🇯🇵',
            'Suecia' => '🇸🇪',
            'Túnez' => '🇹🇳',
            'Bélgica' => '🇧🇪',
            'Egipto' => '🇪🇬',
            'Irán' => '🇮🇷',
            'Nueva Zelanda' => '🇳🇿',
            'España' => '🇪🇸',
            'Cabo Verde' => '🇨🇻',
            'Arabia Saudita' => '🇸🇦',
            'Uruguay' => '🇺🇾',
            'Francia' => '🇫🇷',
            'Senegal' => '🇸🇳',
            'Irak' => '🇮🇶',
            'Noruega' => '🇳🇴',
            'Argentina' => '🇦🇷',
            'Argelia' => '🇩🇿',
            'Austria' => '🇦🇹',
            'Jordania' => '🇯🇴',
            'Portugal' => '🇵🇹',
            'RD Congo' => '🇨🇩',
            'Uzbekistán' => '🇺🇿',
            'Colombia' => '🇨🇴',
            'Inglaterra' => '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
            'Croacia' => '🇭🇷',
            'Ghana' => '🇬🇭',
            'Panamá' => '🇵🇦',
        ];

        $venues = [
            'Ciudad de México' => 'Estadio Azteca, Ciudad de México',
            'Guadalajara' => 'Estadio Akron, Guadalajara',
            'Monterrey' => 'Estadio BBVA, Monterrey',
            'Toronto' => 'BMO Field, Toronto',
            'Vancouver' => 'BC Place, Vancouver',
            'Atlanta' => 'Mercedes-Benz Stadium, Atlanta',
            'Boston' => 'Gillette Stadium, Boston',
            'Dallas' => 'AT&T Stadium, Dallas',
            'Houston' => 'NRG Stadium, Houston',
            'Kansas City' => 'Arrowhead Stadium, Kansas City',
            'Los Ángeles' => 'SoFi Stadium, Los Ángeles',
            'Miami' => 'Hard Rock Stadium, Miami',
            'Nueva Jersey' => 'MetLife Stadium, Nueva Jersey',
            'Philadelphia' => 'Lincoln Financial Field, Philadelphia',
            'San Francisco' => "Levi's Stadium, San Francisco",
            'Seattle' => 'Lumen Field, Seattle',
        ];

        // [match_number, group, date YYYY-MM-DD, time HH:MM (Colombia GMT-5), home, away, city]
        $matches = [
            [1,  'A', '2026-06-11', '14:00', 'México',          'Sudáfrica',           'Ciudad de México'],
            [2,  'A', '2026-06-11', '21:00', 'Corea del Sur',   'República Checa',     'Guadalajara'],
            [3,  'B', '2026-06-12', '14:00', 'Canadá',          'Bosnia y Herzegovina','Toronto'],
            [4,  'D', '2026-06-12', '20:00', 'Estados Unidos',  'Paraguay',            'Los Ángeles'],
            [5,  'B', '2026-06-13', '14:00', 'Qatar',           'Suiza',               'San Francisco'],
            [6,  'C', '2026-06-13', '17:00', 'Brasil',          'Marruecos',           'Nueva Jersey'],
            [7,  'C', '2026-06-13', '20:00', 'Haití',           'Escocia',             'Boston'],
            [8,  'D', '2026-06-13', '23:00', 'Australia',       'Turquía',             'Vancouver'],
            [9,  'E', '2026-06-14', '12:00', 'Alemania',        'Curazao',             'Houston'],
            [10, 'F', '2026-06-14', '15:00', 'Países Bajos',    'Japón',               'Dallas'],
            [11, 'E', '2026-06-14', '18:00', 'Costa de Marfil', 'Ecuador',             'Philadelphia'],
            [12, 'F', '2026-06-14', '21:00', 'Suecia',          'Túnez',               'Monterrey'],
            [13, 'H', '2026-06-15', '11:00', 'España',          'Cabo Verde',          'Atlanta'],
            [14, 'G', '2026-06-15', '14:00', 'Bélgica',         'Egipto',              'Seattle'],
            [15, 'H', '2026-06-15', '17:00', 'Arabia Saudita',  'Uruguay',             'Miami'],
            [16, 'G', '2026-06-15', '20:00', 'Irán',            'Nueva Zelanda',       'Los Ángeles'],
            [17, 'I', '2026-06-16', '14:00', 'Francia',         'Senegal',             'Nueva Jersey'],
            [18, 'I', '2026-06-16', '17:00', 'Irak',            'Noruega',             'Boston'],
            [19, 'J', '2026-06-16', '20:00', 'Argentina',       'Argelia',             'Kansas City'],
            [20, 'J', '2026-06-16', '23:00', 'Austria',         'Jordania',            'San Francisco'],
            [21, 'K', '2026-06-17', '12:00', 'Portugal',        'RD Congo',            'Houston'],
            [22, 'L', '2026-06-17', '15:00', 'Inglaterra',      'Croacia',             'Dallas'],
            [23, 'L', '2026-06-17', '18:00', 'Ghana',           'Panamá',              'Toronto'],
            [24, 'K', '2026-06-17', '21:00', 'Uzbekistán',      'Colombia',            'Ciudad de México'],
            [25, 'A', '2026-06-18', '11:00', 'República Checa', 'Sudáfrica',           'Atlanta'],
            [26, 'B', '2026-06-18', '14:00', 'Suiza',           'Bosnia y Herzegovina','Los Ángeles'],
            [27, 'B', '2026-06-18', '17:00', 'Canadá',          'Qatar',               'Vancouver'],
            [28, 'A', '2026-06-18', '20:00', 'México',          'Corea del Sur',       'Guadalajara'],
            [29, 'D', '2026-06-19', '14:00', 'Estados Unidos',  'Australia',           'Seattle'],
            [30, 'C', '2026-06-19', '17:00', 'Escocia',         'Marruecos',           'Boston'],
            [31, 'C', '2026-06-19', '19:30', 'Brasil',          'Haití',               'Philadelphia'],
            [32, 'D', '2026-06-19', '22:00', 'Turquía',         'Paraguay',            'San Francisco'],
            [33, 'F', '2026-06-20', '12:00', 'Países Bajos',    'Suecia',              'Houston'],
            [34, 'E', '2026-06-20', '15:00', 'Alemania',        'Costa de Marfil',     'Toronto'],
            [35, 'E', '2026-06-20', '19:00', 'Ecuador',         'Curazao',             'Kansas City'],
            [36, 'F', '2026-06-20', '23:00', 'Túnez',           'Japón',               'Monterrey'],
            [37, 'H', '2026-06-21', '11:00', 'España',          'Arabia Saudita',      'Atlanta'],
            [38, 'G', '2026-06-21', '14:00', 'Bélgica',         'Irán',                'Los Ángeles'],
            [39, 'H', '2026-06-21', '17:00', 'Uruguay',         'Cabo Verde',          'Miami'],
            [40, 'G', '2026-06-21', '20:00', 'Nueva Zelanda',   'Egipto',              'Vancouver'],
            [41, 'J', '2026-06-22', '12:00', 'Argentina',       'Austria',             'Dallas'],
            [42, 'I', '2026-06-22', '16:00', 'Francia',         'Irak',                'Philadelphia'],
            [43, 'I', '2026-06-22', '19:00', 'Noruega',         'Senegal',             'Nueva Jersey'],
            [44, 'J', '2026-06-22', '22:00', 'Jordania',        'Argelia',             'San Francisco'],
            [45, 'K', '2026-06-23', '12:00', 'Portugal',        'Uzbekistán',          'Houston'],
            [46, 'L', '2026-06-23', '15:00', 'Inglaterra',      'Ghana',               'Boston'],
            [47, 'L', '2026-06-23', '18:00', 'Panamá',          'Croacia',             'Toronto'],
            [48, 'K', '2026-06-23', '21:00', 'Colombia',        'RD Congo',            'Guadalajara'],
            [49, 'B', '2026-06-24', '14:00', 'Suiza',           'Canadá',              'Vancouver'],
            [50, 'B', '2026-06-24', '14:00', 'Bosnia y Herzegovina', 'Qatar',          'Seattle'],
            [51, 'C', '2026-06-24', '17:00', 'Marruecos',       'Haití',               'Atlanta'],
            [52, 'C', '2026-06-24', '17:00', 'Brasil',          'Escocia',             'Miami'],
            [53, 'A', '2026-06-24', '20:00', 'Sudáfrica',       'Corea del Sur',       'Monterrey'],
            [54, 'A', '2026-06-24', '20:00', 'República Checa', 'México',              'Ciudad de México'],
            [55, 'E', '2026-06-25', '15:00', 'Curazao',         'Costa de Marfil',     'Philadelphia'],
            [56, 'E', '2026-06-25', '15:00', 'Ecuador',         'Alemania',            'Nueva Jersey'],
            [57, 'F', '2026-06-25', '18:00', 'Japón',           'Suecia',              'Dallas'],
            [58, 'F', '2026-06-25', '18:00', 'Túnez',           'Países Bajos',        'Kansas City'],
            [59, 'D', '2026-06-25', '21:00', 'Paraguay',        'Australia',           'San Francisco'],
            [60, 'D', '2026-06-25', '21:00', 'Turquía',         'Estados Unidos',      'Los Ángeles'],
            [61, 'I', '2026-06-26', '14:00', 'Noruega',         'Francia',             'Boston'],
            [62, 'I', '2026-06-26', '14:00', 'Senegal',         'Irak',                'Toronto'],
            [63, 'H', '2026-06-26', '19:00', 'Cabo Verde',      'Arabia Saudita',      'Houston'],
            [64, 'H', '2026-06-26', '19:00', 'Uruguay',         'España',              'Guadalajara'],
            [65, 'G', '2026-06-26', '22:00', 'Egipto',          'Irán',                'Seattle'],
            [66, 'G', '2026-06-26', '22:00', 'Nueva Zelanda',   'Bélgica',             'Vancouver'],
            [67, 'L', '2026-06-27', '16:00', 'Croacia',         'Ghana',               'Philadelphia'],
            [68, 'L', '2026-06-27', '16:00', 'Panamá',          'Inglaterra',          'Nueva Jersey'],
            [69, 'K', '2026-06-27', '18:30', 'Colombia',        'Portugal',            'Miami'],
            [70, 'K', '2026-06-27', '18:30', 'RD Congo',        'Uzbekistán',          'Atlanta'],
            [71, 'J', '2026-06-27', '21:00', 'Argelia',         'Austria',             'Kansas City'],
            [72, 'J', '2026-06-27', '21:00', 'Jordania',        'Argentina',           'Dallas'],
        ];

        $now = Carbon::now();

        foreach ($matches as [$num, $group, $date, $time, $home, $away, $city]) {
            $datetime = Carbon::createFromFormat('Y-m-d H:i', "$date $time", 'America/Bogota');

            DB::table('matches')->updateOrInsert(
                ['match_number' => $num],
                [
                    'phase' => 'grupos',
                    'group_name' => $group,
                    'home_team' => $home,
                    'away_team' => $away,
                    'home_flag' => $flags[$home] ?? null,
                    'away_flag' => $flags[$away] ?? null,
                    'match_datetime' => $datetime->format('Y-m-d H:i:s'),
                    'lock_datetime' => $datetime->copy()->subMinutes(5)->format('Y-m-d H:i:s'),
                    'venue' => $venues[$city] ?? $city,
                    'status' => 'upcoming',
                    'created_at' => $now,
                    'updated_at' => $now,
                ]
            );
        }
    }
}
